name: Rollback to Latest Backup

on:
  workflow_dispatch: # 只允許在 GitHub Actions 頁面手動觸發

jobs:
  rollback:
    name: Rollback to Latest Backup
    runs-on: ubuntu-latest
    steps:
      - name: Execute Rollback on Server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }}
          username: ${{ secrets.REMOTE_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            BACKUP_DIR="/usr/local/tomcat9/webapps/backups"
            TARGET_DIR="/usr/local/tomcat9/webapps/tools"

            echo "Searching for the latest backup in ${BACKUP_DIR}..."

            # 透過按時間排序，尋找最新的備份目錄
            LATEST_BACKUP=$(ls -1t ${BACKUP_DIR} | head -n 1)

            # 檢查是否有備份存在
            if [ -z "${LATEST_BACKUP}" ]; then
              echo "Error: No backups found in ${BACKUP_DIR}."
              exit 1
            fi

            echo "Found latest backup: ${LATEST_BACKUP}"
            echo "Starting rollback process..."

            # 確保目標目錄存在，如果不存在則建立
            mkdir -p ${TARGET_DIR}

            # 清空目前的目標目錄
            echo "Clearing target directory: ${TARGET_DIR}"
            rm -rf ${TARGET_DIR}/*

            # 從最新的備份還原檔案
            # 注意：使用 /* 可以確保只複製目錄下的內容
            echo "Restoring from ${BACKUP_DIR}/${LATEST_BACKUP}/ to ${TARGET_DIR}"
            cp -r ${BACKUP_DIR}/${LATEST_BACKUP}/* ${TARGET_DIR}/

            echo "Rollback completed successfully."
